repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        stages: [push]
      - id: end-of-file-fixer
        stages: [push]
      - id: trailing-whitespace
        stages: [push]
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.45.0
    hooks:
      - id: golangci-lint
        stages: [push]
